//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_SmallTools.ServiceReferenceTools {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTools.IServiceTools")]
    public interface IServiceTools {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTools/DoWork", ReplyAction="http://tempuri.org/IServiceTools/DoWorkResponse")]
        void DoWork();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceToolsChannel : WF_SmallTools.ServiceReferenceTools.IServiceTools, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceToolsClient : System.ServiceModel.ClientBase<WF_SmallTools.ServiceReferenceTools.IServiceTools>, WF_SmallTools.ServiceReferenceTools.IServiceTools {
        
        public ServiceToolsClient() {
        }
        
        public ServiceToolsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceToolsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceToolsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceToolsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
    }
}
